### ISSUE TITLE
Cannot set propert 'domain' ?!?!??!?!

### ISSUE THREAD

**Issue by Lanson2232** [immrmonero/coin-imp#8]
(node:1641) UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'domain' of undefined

i get this error When i want Mine Electroneum

FULL CODE:

(node:2453) UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'domain' of undefined
    at EventEmitter.init (events.js:63:15)
    at EventEmitter (events.js:28:21)
   at Proxy (/rbd/pnpm-volume/4dc99d17-3860-4a57-99ce-2fd98bb74ac1/node_modules/.registry.npmjs.org/web-socket-proxy/1.2.0/node_modules/web-socket-proxy/build/Proxy.js:26:28)
  at getRunner (/rbd/pnpm-volume/4dc99d17-3860-4a57-99ce-2fd98bb74ac1/node_modules/.registry.npmjs.org/coin-imp/1.0.6/node_modules/coin-imp/src/index.js:10:19)
at /app/server.js:6:21
at Object.<anonymous> (/app/server.js:14:3)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
(node:2453) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:2453) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by dezinhop** [comment]
I have the same problem, have you managed to solve it?

**Comment by Lanson2232** [comment]
> I have the same problem, have you managed to solve it?

sorry for answering late, but Electroneum has stopped the mining reward "feature" thats the reason why we cant use it

**Comment by pepe-invest-git** [comment]
https://group-ppp.eu
